services:

  nginx:
    depends_on:
      - front
      # - user-mgmt
      # - game
    container_name: nginx
    image: nginx
    build: ./nginx
    restart: always
    env_file: 
      - .env
    ports:
      - "8443:8443"
    volumes:
      - front_data:/var/www/html
    networks:
      - trs_net
  
  front:
    container_name: front
    build: ./front
    image: front
    volumes:
      - front_data:/app
    env_file:
      - .env
    expose:
      - "2424:2424"
    networks:
       - trs_net

  # db:
  #   image: postgres:alpine3.18
  #   container_name: db-postgres
  #   environment:
  #     POSTGRES_USER: admin
  #     POSTGRES_PASSWORD: 12345
  #     POSTGRES_DB: transcendence
  #   volumes:
  #     - db_data:/var/lib/postgresql/data
  #   networks:
  #      - trs_net

  # user-mgmt:
  #   build:
  #     context: ./user-mgmt
  #   container_name: user-mgmt
  #   depends_on:
  #     - db
  #   environment:
  #     - DATABASE_URL=postgres://admin:12345@db:5432/transcendence
  #   networks:
  #      - trs_net
  #   restart: always
  #   ports:
  #     - "8000:8000"

  # game:
  #   build:
  #     context: ./game
  #   container_name: game
  #   depends_on:
  #     - db
  #   networks:
  #      - trs_net
  #   restart: always

# volumes:
#   db_data:
#     driver: local

volumes:
  front_data:
    driver: local
    driver_opts:
      device: "./front/tools"
      o: bind
      type: none

networks:
  trs_net:
    driver: bridge