services:

  db:
    image: postgres
    container_name: db-postgres
    environment:
      - POSTGRES_USER=${POSTGRE_USER}
      - POSTGRES_PASSWORD=${POSTGRE_PASSWORD}
      - POSTGRES_DB=${POSTGRE_DB}
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - db_data:/var/lib/postgresql/data
      - type: tmpfs
        target: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
       - trs_net

  # user_mgmt:
  #   build:
  #     context: ./back/user_mgmt
  #   container_name: user_mgmt
  #   depends_on:
  #     - db
  #   environment:
  #     - DATABASE_URL=postgres://admin:12345@db:5432/transcendence
  #   networks:
  #      - trs_net
  #   restart: always
  #   volumes:
  #     - user-mgmt:/usr/src/app
  #   ports:
  #     - "8000:8000"

  game:
    build:
      context: ./back/game
    container_name: game
    depends_on:
      - db
    environment:
      - DATABASE_URL={DATABASE_URL}
    networks:
       - trs_net
    restart: always
    volumes:
      - game:/usr/src/app
    ports:
      - "8100:8100"

  # front:
  #   container_name: front
  #   build: ./front
  #   image: front
  #   volumes:
  #     - front_data:/app
  #   env_file:
  #     - .env
  #   expose:
  #     - "2424:2424"
  #   networks:
  #      - trs_net
  
  # nginx:
  #   depends_on:
  #     - front
  #     # - user-mgmt
  #     # - game
  #   container_name: nginx
  #   image: nginx
  #   build: ./nginx
  #   restart: always
  #   env_file: 
  #     - .env
  #   ports:
  #     - "8443:8443"
  #   volumes:
  #     - front_data:/var/www/html
  #   networks:
  #     - trs_net

volumes:
  front_data:
    driver: local
    driver_opts:
      device: "./front/tools"
      o: bind
      type: none
    
  db_data:
    driver: local
    driver_opts:
      type: none
      device: ./postgres

  user-mgmt:
    driver: local
    driver_opts:
      type: none
      device: ./back/user_mgmt
      o: bind
  game:
    driver: local
    driver_opts:
      type: none
      device: ./back/game
      o: bind

networks:
  trs_net:
    driver: bridge
