services:
  # front: pending Dina
  #   build:
  #     context: ./front
  #   container_name: front-node
  #   ports:
  #     - "1026:1026"
  #   networks:
  #      - trs_net

  db:
    image: postgres:alpine3.18
    container_name: db-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: transcendence
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
       - trs_net

  user_mgmt:
    build:
      context: ./back/user_mgmt
    container_name: user_mgmt
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://admin:12345@db:5432/transcendence
    networks:
       - trs_net
    restart: always
    volumes:
      - user-mgmt:/usr/src/app
    ports:
      - "8000:8000"

  game:
    build:
      context: ./back/game
    container_name: game
    depends_on:
      - db
    networks:
       - trs_net
    restart: always
    volumes:
      - game:/usr/src/app
    ports:
      - "8001:8000"

volumes:
  db_data:
    driver: local

  user-mgmt:
    driver: local
    driver_opts:
      type: none
      device: ./back/user_mgmt
      o: bind
  game:
    driver: local
    driver_opts:
      type: none
      device: ./back/game
      o: bind

networks:
  trs_net:
    driver: bridge
